# Generated by Django 3.2.16 on 2022-12-25 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='end_date',
            field=models.DateTimeField(verbose_name='تاریخ انقضاء'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.plan', verbose_name='پکیج'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='start_date',
            field=models.DateTimeField(verbose_name='تاریخ ثبت'),
        ),
    ]
