# Generated by Django 3.2.16 on 2022-12-26 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221225_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='end_date',
            new_name='expire_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='start_date',
        ),
    ]
