# Generated by Django 3.2.16 on 2022-12-26 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_ticket_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departman',
            options={'verbose_name': 'واحد', 'verbose_name_plural': 'واحدها'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت ها'},
        ),
    ]
