# Generated by Django 3.2.16 on 2022-12-26 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20221225_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'ارز',
                'verbose_name_plural': 'ارزها',
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='قیمت فعلی')),
                ('presentation_time', models.DateTimeField(verbose_name='تاریخ و ساعت ارائه')),
                ('entry_point', models.FloatField(verbose_name='نقطه ورود')),
                ('loss_limit', models.FloatField(verbose_name='حد ضرر')),
                ('target1', models.FloatField(blank=True, null=True, verbose_name='تارگت اول')),
                ('target2', models.FloatField(blank=True, null=True, verbose_name='تارگت دوم')),
                ('target3', models.FloatField(blank=True, null=True, verbose_name='تارگت سوم')),
                ('target4', models.FloatField(blank=True, null=True, verbose_name='تارگت چهارم')),
                ('target5', models.FloatField(blank=True, null=True, verbose_name='تارگت پنجم')),
                ('lever', models.FloatField(verbose_name='اهرم')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signals.currency', verbose_name='نام ارز')),
                ('plan', models.ManyToManyField(to='accounts.Plan', verbose_name='پکیج')),
            ],
            options={
                'verbose_name': 'سیگنال',
                'verbose_name_plural': 'سیگنال ها',
            },
        ),
    ]
