# Generated by Django 3.2.16 on 2022-12-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_auto_20221226_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='lever',
            field=models.FloatField(blank=True, null=True, verbose_name='اهرم'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='loss_limit',
            field=models.FloatField(blank=True, null=True, verbose_name='حد ضرر'),
        ),
    ]
